# Generated by Django 2.0.1 on 2018-03-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substation_name', models.CharField(max_length=250)),
                ('HT_CurrentValue', models.FloatField()),
                ('HT_VoltageValue', models.FloatField()),
                ('HT_PowerFactor', models.FloatField()),
                ('LT_CurrentValue', models.FloatField()),
                ('LT_VoltageValue', models.FloatField()),
                ('LT_PowerFactor', models.FloatField()),
            ],
        ),
    ]
